[dev]
publish = "dist"
framework = "#static"
functions = "api"

[build]
publish = "dist"
command = "make dist"
functions = "api"

[build.environment]
GO_VERSION = "1.22.5"
GO_IMPORT_PATH = "github.com/NDoolan360/etyml-app"
GO111MODULE = "on"
