package main

import (
	"math/rand"
	"time"
)

type Term struct {
	Term string `json:"term"`
	Root string `json:"root"`
}

func selectTermsWithCommonRoot(terms []Term, maxAmount int) []Term {
	rand.New(rand.NewSource(time.Now().UnixNano()))

	// Randomly select a root
	idx := rand.Intn(len(terms))
	root := terms[idx].Root

	// Filter the term list to only contain terms with that root
	sameRootTerms := make([]Term, 0)
	for _, t := range terms {
		if t.Root == root {
			sameRootTerms = append(sameRootTerms, t)
		}
	}

	// Randomly select three terms with that root
	rand.Shuffle(len(sameRootTerms), func(i, j int) {
		sameRootTerms[i], sameRootTerms[j] =
			sameRootTerms[j], sameRootTerms[i]
	})

	// If can't make enough values, try again
	if len(sameRootTerms) < maxAmount {
		selectTermsWithCommonRoot(terms, maxAmount)
	}

	return sameRootTerms[0:maxAmount]
}

var englishPIETerms = []Term{
	{"accept", "*keh₂p-"},
	{"acceptable", "*keh₂p-"},
	{"acceptance", "*keh₂p-"},
	{"accepted", "*keh₂p-"},
	{"achieve", "*keh₂p-"},
	{"behavior", "*keh₂p-"},
	{"behavioral", "*keh₂p-"},
	{"cable", "*keh₂p-"},
	{"capability", "*keh₂p-"},
	{"capable", "*keh₂p-"},
	{"capacity", "*keh₂p-"},
	{"capture", "*keh₂p-"},
	{"cash", "*keh₂p-"},
	{"catch", "*keh₂p-"},
	{"chase", "*keh₂p-"},
	{"concept", "*keh₂p-"},
	{"copper", "*keh₂p-"},
	{"except", "*keh₂p-"},
	{"exception", "*keh₂p-"},
	{"exceptional", "*keh₂p-"},
	{"haven", "*keh₂p-"},
	{"head", "*keh₂p-"},
	{"heavily", "*keh₂p-"},
	{"heavy", "*keh₂p-"},
	{"municipal", "*keh₂p-"},
	{"occupation", "*keh₂p-"},
	{"occupational", "*keh₂p-"},
	{"participant", "*keh₂p-"},
	{"participate", "*keh₂p-"},
	{"participation", "*keh₂p-"},
	{"perception", "*keh₂p-"},
	{"prince", "*keh₂p-"},
	{"princess", "*keh₂p-"},
	{"principal", "*keh₂p-"},
	{"principle", "*keh₂p-"},
	{"purchase", "*keh₂p-"},
	{"receipt", "*keh₂p-"},
	{"receive", "*keh₂p-"},
	{"receiver", "*keh₂p-"},
	{"reception", "*keh₂p-"},
	{"receptor", "*keh₂p-"},
	{"recipe", "*keh₂p-"},
	{"recipient", "*keh₂p-"},
	{"recover", "*keh₂p-"},
	{"recovery", "*keh₂p-"},
	{"affect", "*dʰeh₁-"},
	{"artificial", "*dʰeh₁-"},
	{"beneficial", "*dʰeh₁-"},
	{"benefit", "*dʰeh₁-"},
	{"costume", "*dʰeh₁-"},
	{"custom", "*dʰeh₁-"},
	{"effect", "*dʰeh₁-"},
	{"effective", "*dʰeh₁-"},
	{"efficient", "*dʰeh₁-"},
	{"ethical", "*dʰeh₁-"},
	{"ethnic", "*dʰeh₁-"},
	{"facility", "*dʰeh₁-"},
	{"fact", "*dʰeh₁-"},
	{"factor", "*dʰeh₁-"},
	{"factory", "*dʰeh₁-"},
	{"familiar", "*dʰeh₁-"},
	{"fan", "*dʰeh₁-"},
	{"fashion", "*dʰeh₁-"},
	{"fax", "*dʰeh₁-"},
	{"festival", "*dʰeh₁-"},
	{"fetish", "*dʰeh₁-"},
	{"incredible", "*dʰeh₁-"},
	{"infection", "*dʰeh₁-"},
	{"mathematics", "*dʰeh₁-"},
	{"modification", "*dʰeh₁-"},
	{"modify", "*dʰeh₁-"},
	{"perfect", "*dʰeh₁-"},
	{"satisfaction", "*dʰeh₁-"},
	{"satisfy", "*dʰeh₁-"},
	{"scientific", "*dʰeh₁-"},
	{"significance", "*dʰeh₁-"},
	{"significant", "*dʰeh₁-"},
	{"sufficient", "*dʰeh₁-"},
	{"synthesis", "*dʰeh₁-"},
	{"synthetic", "*dʰeh₁-"},
	{"theme", "*dʰeh₁-"},
	{"thesis", "*dʰeh₁-"},
	{"verification", "*dʰeh₁-"},
	{"verify", "*dʰeh₁-"},
	{"wood", "*dʰeh₁-"},
	{"word", "*dʰeh₁-"},
	{"either", "*kʷ-"},
	{"neither", "*kʷ-"},
	{"quantity", "*kʷ-"},
	{"whether", "*kʷ-"},
	{"whom", "*kʷ-"},
	{"whose", "*kʷ-"},
	{"admit", "*mey- "},
	{"commission", "*mey- "},
	{"commit", "*mey- "},
	{"committee", "*mey- "},
	{"common", "*mey- "},
	{"communicate", "*mey- "},
	{"immune", "*mey- "},
	{"mad", "*mey- "},
	{"mass", "*mey- "},
	{"mean", "*mey- "},
	{"minimal", "*mey- "},
	{"minimum", "*mey- "},
	{"minister", "*mey- "},
	{"minor", "*mey- "},
	{"minus", "*mey- "},
	{"miss", "*mey- "},
	{"mission", "*mey- "},
	{"municipal", "*mey- "},
	{"mutual", "*mey- "},
	{"permit", "*mey- "},
	{"promise", "*mey- "},
	{"submit", "*mey- "},
	{"transmission", "*mey- "},
	{"acrobat", "*gʷem-"},
	{"adventure", "*gʷem-"},
	{"base", "*gʷem-"},
	{"basic", "*gʷem-"},
	{"basis", "*gʷem-"},
	{"bass", "*gʷem-"},
	{"become", "*gʷem-"},
	{"come", "*gʷem-"},
	{"convenience", "*gʷem-"},
	{"convention", "*gʷem-"},
	{"cum", "*gʷem-"},
	{"diabetes", "*gʷem-"},
	{"event", "*gʷem-"},
	{"eventually", "*gʷem-"},
	{"intervention", "*gʷem-"},
	{"prevent", "*gʷem-"},
	{"revenue", "*gʷem-"},
	{"venture", "*gʷem-"},
	{"venue", "*gʷem-"},
	{"engine", "*ǵenh₁-"},
	{"engineer", "*ǵenh₁-"},
	{"gender", "*ǵenh₁-"},
	{"gene", "*ǵenh₁-"},
	{"genealogy", "*ǵenh₁-"},
	{"generate", "*ǵenh₁-"},
	{"generation", "*ǵenh₁-"},
	{"generic", "*ǵenh₁-"},
	{"genesis", "*ǵenh₁-"},
	{"genetic", "*ǵenh₁-"},
	{"genre", "*ǵenh₁-"},
	{"indigenous", "*ǵenh₁-"},
	{"kind", "*ǵenh₁-"},
	{"king", "*ǵenh₁-"},
	{"nation", "*ǵenh₁-"},
	{"native", "*ǵenh₁-"},
	{"natural", "*ǵenh₁-"},
	{"nature", "*ǵenh₁-"},
	{"Renaissance", "*ǵenh₁-"},
	{"associate", "*sekʷ-"},
	{"association", "*sekʷ-"},
	{"execute", "*sekʷ-"},
	{"execution", "*sekʷ-"},
	{"executive", "*sekʷ-"},
	{"pursue", "*sekʷ-"},
	{"saw", "*sekʷ-"},
	{"sequence", "*sekʷ-"},
	{"signal", "*sekʷ-"},
	{"signature", "*sekʷ-"},
	{"social", "*sekʷ-"},
	{"society", "*sekʷ-"},
	{"subsequent", "*sekʷ-"},
	{"subsequently", "*sekʷ-"},
	{"sue", "*sekʷ-"},
	{"suit", "*sekʷ-"},
	{"suite", "*sekʷ-"},
	{"export", "*per- "},
	{"ferry", "*per- "},
	{"ford", "*per- "},
	{"opportunity", "*per- "},
	{"participate", "*per- "},
	{"particle", "*per- "},
	{"particular", "*per- "},
	{"port", "*per- "},
	{"portable", "*per- "},
	{"portal", "*per- "},
	{"porter", "*per- "},
	{"portion", "*per- "},
	{"practical", "*per- "},
	{"practice", "*per- "},
	{"proportion", "*per- "},
	{"sport", "*per- "},
	{"fee", "*peḱ-"},
	{"fellow", "*peḱ-"},
	{"feud", "*peḱ-"},
	{"constitution", "*steh₂-"},
	{"constitutional", "*steh₂-"},
	{"contest", "*steh₂-"},
	{"instant", "*steh₂-"},
	{"protest", "*steh₂-"},
	{"rest", "*steh₂-"},
	{"stable", "*steh₂-"},
	{"stage", "*steh₂-"},
	{"stand", "*steh₂-"},
	{"standing", "*steh₂-"},
	{"static", "*steh₂-"},
	{"station", "*steh₂-"},
	{"status", "*steh₂-"},
	{"stay", "*steh₂-"},
	{"stem", "*steh₂-"},
	{"act", "*h₂eǵ-"},
	{"active", "*h₂eǵ-"},
	{"actor", "*h₂eǵ-"},
	{"agenda", "*h₂eǵ-"},
	{"agent", "*h₂eǵ-"},
	{"digest", "*h₂eǵ-"},
	{"embassy", "*h₂eǵ-"},
	{"essay", "*h₂eǵ-"},
	{"exact", "*h₂eǵ-"},
	{"navigate", "*h₂eǵ-"},
	{"reaction", "*h₂eǵ-"},
	{"strategy", "*h₂eǵ-"},
	{"suggest", "*h₂eǵ-"},
	{"transaction", "*h₂eǵ-"},
	{"aspect", "*speḱ-"},
	{"despite", "*speḱ-"},
	{"especially", "*speḱ-"},
	{"expect", "*speḱ-"},
	{"perspective", "*speḱ-"},
	{"prospect", "*speḱ-"},
	{"respect", "*speḱ-"},
	{"scope", "*speḱ-"},
	{"species", "*speḱ-"},
	{"spectacular", "*speḱ-"},
	{"spectrum", "*speḱ-"},
	{"spice", "*speḱ-"},
	{"spy", "*speḱ-"},
	{"suspect", "*speḱ-"},
	{"blast", "*-tus"},
	{"concept", "*-tus"},
	{"costume", "*-tus"},
	{"craft", "*-tus"},
	{"death", "*-tus"},
	{"draft", "*-tus"},
	{"event", "*-tus"},
	{"exit", "*-tus"},
	{"ford", "*-tus"},
	{"latitude", "*-tus"},
	{"pace", "*-tus"},
	{"sense", "*-tus"},
	{"spirit", "*-tus"},
	{"catalogue", "*leǵ-"},
	{"collect", "*leǵ-"},
	{"collection", "*leǵ-"},
	{"collective", "*leǵ-"},
	{"collector", "*leǵ-"},
	{"election", "*leǵ-"},
	{"elegant", "*leǵ-"},
	{"eligible", "*leǵ-"},
	{"elite", "*leǵ-"},
	{"intellectual", "*leǵ-"},
	{"intelligent", "*leǵ-"},
	{"lecture", "*leǵ-"},
	{"legend", "*leǵ-"},
	{"lesson", "*leǵ-"},
	{"mile", "*sem-"},
	{"million", "*sem-"},
	{"seem", "*sem-"},
	{"semi", "*sem-"},
	{"similar", "*sem-"},
	{"similarly", "*sem-"},
	{"simple", "*sem-"},
	{"simulation", "*sem-"},
	{"single", "*sem-"},
	{"soft", "*sem-"},
	{"symbol", "*sem-"},
	{"symposium", "*sem-"},
	{"synopsis", "*sem-"},
	{"synthesis", "*sem-"},
	{"addition", "*deh₃-"},
	{"command", "*deh₃-"},
	{"demand", "*deh₃-"},
	{"donate", "*deh₃-"},
	{"donation", "*deh₃-"},
	{"donor", "*deh₃-"},
	{"dose", "*deh₃-"},
	{"edit", "*deh₃-"},
	{"edition", "*deh₃-"},
	{"editor", "*deh₃-"},
	{"mandatory", "*deh₃-"},
	{"tradition", "*deh₃-"},
	{"vendor", "*deh₃-"},
	{"adult", "*h₂el- "},
	{"alias", "*h₂el- "},
	{"alien", "*h₂el- "},
	{"alter", "*h₂el- "},
	{"alternate", "*h₂el- "},
	{"alumni", "*h₂el- "},
	{"elder", "*h₂el- "},
	{"element", "*h₂el- "},
	{"ellen", "*h₂el- "},
	{"else", "*h₂el- "},
	{"OK", "*h₂el- "},
	{"ultimate", "*h₂el- "},
	{"ultra", "*h₂el- "},
	{"advice", "*weyd-"},
	{"advise", "*weyd-"},
	{"evidence", "*weyd-"},
	{"idea", "*weyd-"},
	{"provision", "*weyd-"},
	{"story", "*weyd-"},
	{"television", "*weyd-"},
	{"visible", "*weyd-"},
	{"vision", "*weyd-"},
	{"visual", "*weyd-"},
	{"wisdom", "*weyd-"},
	{"wise", "*weyd-"},
	{"witness", "*weyd-"},
	{"bear", "*bʰer-"},
	{"birth", "*bʰer-"},
	{"burden", "*bʰer-"},
	{"differ", "*bʰer-"},
	{"difference", "*bʰer-"},
	{"fortune", "*bʰer-"},
	{"offer", "*bʰer-"},
	{"prefer", "*bʰer-"},
	{"preference", "*bʰer-"},
	{"refer", "*bʰer-"},
	{"reference", "*bʰer-"},
	{"suffer", "*bʰer-"},
	{"transfer", "*bʰer-"},
	{"brain", "*men- "},
	{"demo", "*men- "},
	{"demonstrate", "*men- "},
	{"manor", "*men- "},
	{"mathematics", "*men- "},
	{"mint", "*men- "},
	{"monster", "*men- "},
	{"Montana", "*men- "},
	{"mouth", "*men- "},
	{"museum", "*men- "},
	{"musical", "*men- "},
	{"permanent", "*men- "},
	{"remain", "*men- "},
	{"conduct", "*dewk-"},
	{"duke", "*dewk-"},
	{"educational", "*dewk-"},
	{"introduce", "*dewk-"},
	{"introduction", "*dewk-"},
	{"produce", "*dewk-"},
	{"production", "*dewk-"},
	{"productive", "*dewk-"},
	{"reduce", "*dewk-"},
	{"reduction", "*dewk-"},
	{"tie", "*dewk-"},
	{"touch", "*dewk-"},
	{"toy", "*dewk-"},
	{"correct", "*h₃reǵ-"},
	{"dick", "*h₃reǵ-"},
	{"dress", "*h₃reǵ-"},
	{"OK", "*h₃reǵ-"},
	{"regime", "*h₃reǵ-"},
	{"region", "*h₃reǵ-"},
	{"regional", "*h₃reǵ-"},
	{"resource", "*h₃reǵ-"},
	{"rich", "*h₃reǵ-"},
	{"roy", "*h₃reǵ-"},
	{"royal", "*h₃reǵ-"},
	{"royalty", "*h₃reǵ-"},
	{"rule", "*h₃reǵ-"},
	{"emotional", "*mew-"},
	{"mobile", "*mew-"},
	{"mobility", "*mew-"},
	{"motion", "*mew-"},
	{"motor", "*mew-"},
	{"move", "*mew-"},
	{"movement", "*mew-"},
	{"promote", "*mew-"},
	{"promotion", "*mew-"},
	{"promotional", "*mew-"},
	{"remote", "*mew-"},
	{"removal", "*mew-"},
	{"remove", "*mew-"},
	{"alarm", "*h₂er-"},
	{"arm", "*h₂er-"},
	{"army", "*h₂er-"},
	{"artificial", "*h₂er-"},
	{"artist", "*h₂er-"},
	{"artistic", "*h₂er-"},
	{"harmony", "*h₂er-"},
	{"ordinary", "*h₂er-"},
	{"Ralph", "*h₂er-"},
	{"ratio", "*h₂er-"},
	{"ready", "*h₂er-"},
	{"reason", "*h₂er-"},
	{"harbor", "*ker-"},
	{"harry", "*ker-"},
	{"herald", "*ker-"},
	{"rugby", "*ker-"},
	{"Walter", "*ker-"},
	{"approach", "*per-"},
	{"experience", "*per-"},
	{"experiment", "*per-"},
	{"expert", "*per-"},
	{"fear", "*per-"},
	{"parent", "*per-"},
	{"preparation", "*per-"},
	{"prepare", "*per-"},
	{"prime", "*per-"},
	{"provision", "*per-"},
	{"ban", "*bʰeh₂-"},
	{"bee", "*bʰeh₂-"},
	{"ben", "*bʰeh₂-"},
	{"emphasis", "*bʰeh₂-"},
	{"fabulous", "*bʰeh₂-"},
	{"fate", "*bʰeh₂-"},
	{"infant", "*bʰeh₂-"},
	{"phase", "*bʰeh₂-"},
	{"profession", "*bʰeh₂-"},
	{"professor", "*bʰeh₂-"},
	{"telephone", "*bʰeh₂-"},
	{"addiction", "*deyḱ-"},
	{"condition", "*deyḱ-"},
	{"dictionary", "*deyḱ-"},
	{"indicate", "*deyḱ-"},
	{"indicator", "*deyḱ-"},
	{"judge", "*deyḱ-"},
	{"prediction", "*deyḱ-"},
	{"syndicate", "*deyḱ-"},
	{"teach", "*deyḱ-"},
	{"toe", "*deyḱ-"},
	{"agriculture", "*kʷel-"},
	{"bicycle", "*kʷel-"},
	{"collar", "*kʷel-"},
	{"culture", "*kʷel-"},
	{"cycle", "*kʷel-"},
	{"motorcycle", "*kʷel-"},
	{"polar", "*kʷel-"},
	{"pole", "*kʷel-"},
	{"telephone", "*kʷel-"},
	{"wheel", "*kʷel-"},
	{"attempt", "*tend-"},
	{"attend", "*tend-"},
	{"extend", "*tend-"},
	{"extent", "*tend-"},
	{"intense", "*tend-"},
	{"intensive", "*tend-"},
	{"intent", "*tend-"},
	{"intention", "*tend-"},
	{"tend", "*tend-"},
	{"tension", "*tend-"},
	{"certain", "*krey-"},
	{"concern", "*krey-"},
	{"crime", "*krey-"},
	{"criminal", "*krey-"},
	{"crisis", "*krey-"},
	{"critical", "*krey-"},
	{"discretion", "*krey-"},
	{"discrimination", "*krey-"},
	{"secret", "*krey-"},
	{"secretary", "*krey-"},
	{"cognitive", "*ǵneh₃-"},
	{"con", "*ǵneh₃-"},
	{"diagnosis", "*ǵneh₃-"},
	{"gnome", "*ǵneh₃-"},
	{"ignore", "*ǵneh₃-"},
	{"ken", "*ǵneh₃-"},
	{"knowledge", "*ǵneh₃-"},
	{"noble", "*ǵneh₃-"},
	{"recognition", "*ǵneh₃-"},
	{"recognize", "*ǵneh₃-"},
	{"complete", "*pleh₁-"},
	{"comply", "*pleh₁-"},
	{"fill", "*pleh₁-"},
	{"folk", "*pleh₁-"},
	{"implement", "*pleh₁-"},
	{"plain", "*pleh₁-"},
	{"plenty", "*pleh₁-"},
	{"plus", "*pleh₁-"},
	{"supply", "*pleh₁-"},
	{"surplus", "*pleh₁-"},
	{"freight", "*pro-"},
	{"proceed", "*pro-"},
	{"produce", "*pro-"},
	{"profit", "*pro-"},
	{"progress", "*pro-"},
	{"projection", "*pro-"},
	{"promote", "*pro-"},
	{"protect", "*pro-"},
	{"protest", "*pro-"},
	{"pursue", "*pro-"},
	{"voluntary", "*welh₁-"},
	{"volunteer", "*welh₁-"},
	{"arrange", "*(s)ker- "},
	{"circle", "*(s)ker- "},
	{"cross", "*(s)ker- "},
	{"crown", "*(s)ker- "},
	{"crucial", "*(s)ker- "},
	{"curve", "*(s)ker- "},
	{"range", "*(s)ker- "},
	{"ring", "*(s)ker- "},
	{"sharp", "*(s)ker- "},
	{"assess", "*sed-"},
	{"chair", "*sed-"},
	{"method", "*sed-"},
	{"period", "*sed-"},
	{"residence", "*sed-"},
	{"resident", "*sed-"},
	{"seat", "*sed-"},
	{"session", "*sed-"},
	{"sit", "*sed-"},
	{"contain", "*ten-"},
	{"entertainment", "*ten-"},
	{"maintain", "*ten-"},
	{"maintenance", "*ten-"},
	{"obtain", "*ten-"},
	{"retain", "*ten-"},
	{"retention", "*ten-"},
	{"tone", "*ten-"},
	{"tune", "*ten-"},
	{"desert", "*ser- "},
	{"hero", "*ser- "},
	{"hormone", "*ser- "},
	{"insert", "*ser- "},
	{"observe", "*ser- "},
	{"preserve", "*ser- "},
	{"reserve", "*ser- "},
	{"serve", "*ser- "},
	{"sort", "*ser- "},
	{"acid", "*h₂eḱ-"},
	{"acrobat", "*h₂eḱ-"},
	{"acute", "*h₂eḱ-"},
	{"cute", "*h₂eḱ-"},
	{"ear", "*h₂eḱ-"},
	{"edge", "*h₂eḱ-"},
	{"hear", "*h₂eḱ-"},
	{"oxygen", "*h₂eḱ-"},
	{"adverse", "*wert-"},
	{"convert", "*wert-"},
	{"divorce", "*wert-"},
	{"reverse", "*wert-"},
	{"verse", "*wert-"},
	{"versus", "*wert-"},
	{"weird", "*wert-"},
	{"worth", "*wert-"},
	{"amount", "*men-"},
	{"automatic", "*men-"},
	{"comment", "*men-"},
	{"mental", "*men-"},
	{"mind", "*men-"},
	{"monitor", "*men-"},
	{"mount", "*men-"},
	{"mountain", "*men-"},
	{"apparent", "*peh₂-"},
	{"appear", "*peh₂-"},
	{"companion", "*peh₂-"},
	{"father", "*peh₂-"},
	{"feed", "*peh₂-"},
	{"foster", "*peh₂-"},
	{"Pan", "*peh₂-"},
	{"transparent", "*peh₂-"},
	{"Atlantic", "*telh₂- "},
	{"atlas", "*telh₂- "},
	{"relate", "*telh₂- "},
	{"relation", "*telh₂- "},
	{"relative", "*telh₂- "},
	{"talent", "*telh₂- "},
	{"translate", "*telh₂- "},
	{"translation", "*telh₂- "},
	{"double", "*pel- "},
	{"fell", "*pel- "},
	{"felt", "*pel- "},
	{"filter", "*pel- "},
	{"polish", "*pel- "},
	{"pulse", "*pel- "},
	{"push", "*pel- "},
	{"simple", "*pel- "},
	{"entire", "*teh₂g-"},
	{"integer", "*teh₂g-"},
	{"syntax", "*teh₂g-"},
	{"task", "*teh₂g-"},
	{"taste", "*teh₂g-"},
	{"tax", "*teh₂g-"},
	{"taxation", "*teh₂g-"},
	{"taxi", "*teh₂g-"},
	{"equivalent", "*h₂welh₁-"},
	{"herald", "*h₂welh₁-"},
	{"invalid", "*h₂welh₁-"},
	{"Valentine", "*h₂welh₁-"},
	{"valid", "*h₂welh₁-"},
	{"validation", "*h₂welh₁-"},
	{"Walter", "*h₂welh₁-"},
	{"wool", "*h₂welh₁-"},
	{"guard", "*wer-"},
	{"regard", "*wer-"},
	{"reward", "*wer-"},
	{"ward", "*wer-"},
	{"warm", "*wer-"},
	{"wear", "*wer-"},
	{"medical", "*med-"},
	{"medicine", "*med-"},
	{"mode", "*med-"},
	{"moderate", "*med-"},
	{"moderator", "*med-"},
	{"modern", "*med-"},
	{"module", "*med-"},
	{"mood", "*med-"},
	{"ability", "*gʰeh₁bʰ-"},
	{"able", "*gʰeh₁bʰ-"},
	{"debt", "*gʰeh₁bʰ-"},
	{"doubt", "*gʰeh₁bʰ-"},
	{"due", "*gʰeh₁bʰ-"},
	{"exhibit", "*gʰeh₁bʰ-"},
	{"habitat", "*gʰeh₁bʰ-"},
	{"abortion", "*h₃er-"},
	{"earn", "*h₃er-"},
	{"Oriental", "*h₃er-"},
	{"orientation", "*h₃er-"},
	{"origin", "*h₃er-"},
	{"random", "*h₃er-"},
	{"run", "*h₃er-"},
	{"absent", "*h₁es-"},
	{"essence", "*h₁es-"},
	{"essential", "*h₁es-"},
	{"interest", "*h₁es-"},
	{"possible", "*h₁es-"},
	{"potential", "*h₁es-"},
	{"sin", "*h₁es-"},
	{"age", "*h₂ey-"},
	{"either", "*h₂ey-"},
	{"eternal", "*h₂ey-"},
	{"ever", "*h₂ey-"},
	{"juvenile", "*h₂ey-"},
	{"medieval", "*h₂ey-"},
	{"young", "*h₂ey-"},
	{"appendix", "*(s)pend-"},
	{"depend", "*(s)pend-"},
	{"expenditure", "*(s)pend-"},
	{"expense", "*(s)pend-"},
	{"pendant", "*(s)pend-"},
	{"pound", "*(s)pend-"},
	{"spend", "*(s)pend-"},
	{"bound", "*bʰuH-"},
	{"future", "*bʰuH-"},
	{"physical", "*bʰuH-"},
	{"physics", "*bʰuH-"},
	{"probe", "*bʰuH-"},
	{"proof", "*bʰuH-"},
	{"prove", "*bʰuH-"},
	{"cancer", "*(s)ker-"},
	{"score", "*(s)ker-"},
	{"screen", "*(s)ker-"},
	{"share", "*(s)ker-"},
	{"shirt", "*(s)ker-"},
	{"short", "*(s)ker-"},
	{"skirt", "*(s)ker-"},
	{"cargo", "*ḱers-"},
	{"charge", "*ḱers-"},
	{"courier", "*ḱers-"},
	{"curriculum", "*ḱers-"},
	{"horse", "*ḱers-"},
	{"occur", "*ḱers-"},
	{"rush", "*ḱers-"},
	{"compete", "*peth₂-"},
	{"expand", "*peth₂-"},
	{"pace", "*peth₂-"},
	{"patent", "*peth₂-"},
	{"pen", "*peth₂-"},
	{"petition", "*peth₂-"},
	{"repeat", "*peth₂-"},
	{"copy", "*h₃ep-"},
	{"officer", "*h₃ep-"},
	{"official", "*h₃ep-"},
	{"opera", "*h₃ep-"},
	{"operate", "*h₃ep-"},
	{"operational", "*h₃ep-"},
	{"operator", "*h₃ep-"},
	{"meal", "*meh₁-"},
	{"measure", "*meh₁-"},
	{"meter", "*meh₁-"},
	{"month", "*meh₁-"},
	{"moon", "*meh₁-"},
	{"simple", "*meh₁-"},
	{"verification", "*weh₁-"},
	{"verify", "*weh₁-"},
	{"verdict", "*weh₁-"},
	{"absolute", "*lewh₃-"},
	{"laundry", "*lewh₃-"},
	{"resolution", "*lewh₃-"},
	{"resolve", "*lewh₃-"},
	{"solution", "*lewh₃-"},
	{"solve", "*lewh₃-"},
	{"adjacent", "*(H)yeh₁-"},
	{"ease", "*(H)yeh₁-"},
	{"easy", "*(H)yeh₁-"},
	{"jet", "*(H)yeh₁-"},
	{"object", "*(H)yeh₁-"},
	{"projection", "*(H)yeh₁-"},
	{"architect", "*tetḱ-"},
	{"architecture", "*tetḱ-"},
	{"context", "*tetḱ-"},
	{"technical", "*tetḱ-"},
	{"technician", "*tetḱ-"},
	{"technique", "*tetḱ-"},
	{"assume", "*h₁em-"},
	{"example", "*h₁em-"},
	{"exempt", "*h₁em-"},
	{"premium", "*h₁em-"},
	{"redeem", "*h₁em-"},
	{"vintage", "*h₁em-"},
	{"camera", "*kh₂em-"},
	{"camp", "*kh₂em-"},
	{"campaign", "*kh₂em-"},
	{"campus", "*kh₂em-"},
	{"champion", "*kh₂em-"},
	{"championship", "*kh₂em-"},
	{"clause", "*(s)kleh₂w-"},
	{"close", "*(s)kleh₂w-"},
	{"exclude", "*(s)kleh₂w-"},
	{"exclusive", "*(s)kleh₂w-"},
	{"inclusion", "*(s)kleh₂w-"},
	{"inclusive", "*(s)kleh₂w-"},
	{"compound", "*tḱey-"},
	{"deposit", "*tḱey-"},
	{"exposure", "*tḱey-"},
	{"position", "*tḱey-"},
	{"proposal", "*tḱey-"},
	{"suppose", "*tḱey-"},
	{"comprehensive", "*gʰed-"},
	{"enterprise", "*gʰed-"},
	{"forget", "*gʰed-"},
	{"guess", "*gʰed-"},
	{"prison", "*gʰed-"},
	{"surprise", "*gʰed-"},
	{"confidence", "*bʰeydʰ-"},
	{"confident", "*bʰeydʰ-"},
	{"confidential", "*bʰeydʰ-"},
	{"faith", "*bʰeydʰ-"},
	{"federal", "*bʰeydʰ-"},
	{"federation", "*bʰeydʰ-"},
	{"create", "*ḱer- "},
	{"creation", "*ḱer- "},
	{"creator", "*ḱer- "},
	{"crew", "*ḱer- "},
	{"decrease", "*ḱer- "},
	{"increase", "*ḱer- "},
	{"floor", "*pleh₂-"},
	{"palm", "*pleh₂-"},
	{"piano", "*pleh₂-"},
	{"plain", "*pleh₂-"},
	{"plane", "*pleh₂-"},
	{"pleasure", "*pleh₂-"},
	{"grass", "*gʰreh₁-"},
	{"gray", "*gʰreh₁-"},
	{"green", "*gʰreh₁-"},
	{"grey", "*gʰreh₁-"},
	{"grow", "*gʰreh₁-"},
	{"growth", "*gʰreh₁-"},
	{"mortality", "*mer-"},
	{"mortgage", "*mer-"},
	{"murder", "*mer-"},
	{"accident", "*ḱh₂d-"},
	{"casual", "*ḱh₂d-"},
	{"chance", "*ḱh₂d-"},
	{"incident", "*ḱh₂d-"},
	{"occasion", "*ḱh₂d-"},
	{"afraid", "*preyH-"},
	{"appropriate", "*preyH-"},
	{"freedom", "*preyH-"},
	{"friend", "*preyH-"},
	{"proper", "*preyH-"},
	{"antique", "*h₃ekʷ-"},
	{"eye", "*h₃ekʷ-"},
	{"optics", "*h₃ekʷ-"},
	{"synopsis", "*h₃ekʷ-"},
	{"window", "*h₃ekʷ-"},
	{"application", "*pleḱ-"},
	{"apply", "*pleḱ-"},
	{"complex", "*pleḱ-"},
	{"display", "*pleḱ-"},
	{"explicit", "*pleḱ-"},
	{"berry", "*bʰerǵʰ-"},
	{"effort", "*bʰerǵʰ-"},
	{"fort", "*bʰerǵʰ-"},
	{"piano", "*bʰerǵʰ-"},
	{"rugby", "*bʰerǵʰ-"},
	{"boulevard", "*werǵ-"},
	{"energy", "*werǵ-"},
	{"organ", "*werǵ-"},
	{"organic", "*werǵ-"},
	{"wright", "*werǵ-"},
	{"butter", "*tewh₂-"},
	{"soma", "*tewh₂-"},
	{"thousand", "*tewh₂-"},
	{"thumb", "*tewh₂-"},
	{"tumor", "*tewh₂-"},
	{"catholic", "*solh₂-"},
	{"safe", "*solh₂-"},
	{"sol", "*solh₂-"},
	{"sold", "*solh₂-"},
	{"solid", "*solh₂-"},
	{"client", "*ḱley-"},
	{"climate", "*ḱley-"},
	{"clinic", "*ḱley-"},
	{"clinical", "*ḱley-"},
	{"decline", "*ḱley-"},
	{"construct", "*strew-"},
	{"construction", "*strew-"},
	{"destroy", "*strew-"},
	{"destruction", "*strew-"},
	{"strain", "*strew-"},
	{"count", "*pewH-"},
	{"deputy", "*pewH-"},
	{"dispute", "*pewH-"},
	{"pure", "*pewH-"},
	{"reputation", "*pewH-"},
	{"decide", "*kh₂eyd-"},
	{"decision", "*kh₂eyd-"},
	{"hit", "*kh₂eyd-"},
	{"precise", "*kh₂eyd-"},
	{"precision", "*kh₂eyd-"},
	{"detect", "*(s)teg- "},
	{"protect", "*(s)teg- "},
	{"stack", "*(s)teg- "},
	{"thick", "*(s)teg- "},
	{"tile", "*(s)teg- "},
	{"district", "*streyg-"},
	{"strain", "*streyg-"},
	{"stress", "*streyg-"},
	{"strict", "*streyg-"},
	{"strike", "*streyg-"},
	{"dynamic", "*dewh₂-"},
	{"tool", "*dewh₂-"},
	{"toolbar", "*dewh₂-"},
	{"toolbox", "*dewh₂-"},
	{"town", "*dewh₂-"},
	{"economic", "*weyḱ-"},
	{"economics", "*weyḱ-"},
	{"economy", "*weyḱ-"},
	{"parish", "*weyḱ-"},
	{"villa", "*weyḱ-"},
	{"economic", "*nem-"},
	{"economics", "*nem-"},
	{"economy", "*nem-"},
	{"numerical", "*nem-"},
	{"numerous", "*nem-"},
	{"either", "*-teros"},
	{"external", "*-teros"},
	{"neither", "*-teros"},
	{"priest", "*-teros"},
	{"whether", "*-teros"},
	{"encyclopedia", "*peh₂w-"},
	{"few", "*peh₂w-"},
	{"pool", "*peh₂w-"},
	{"poor", "*peh₂w-"},
	{"poverty", "*peh₂w-"},
	{"exit", "*h₁ey-"},
	{"initial", "*h₁ey-"},
	{"issue", "*h₁ey-"},
	{"transit", "*h₁ey-"},
	{"transition", "*h₁ey-"},
	{"fan", "*h₂weh₁-"},
	{"weather", "*h₂weh₁-"},
	{"wind", "*h₂weh₁-"},
	{"window", "*h₂weh₁-"},
	{"wing", "*h₂weh₁-"},
	{"foundation", "*ǵʰewd-"},
	{"fusion", "*ǵʰewd-"},
	{"refund", "*ǵʰewd-"},
	{"refuse", "*ǵʰewd-"},
	{"yet", "*ǵʰewd-"},
	{"league", "*leyǵ-"},
	{"liable", "*leyǵ-"},
	{"obligation", "*leyǵ-"},
	{"rely", "*leyǵ-"},
	{"Louis", "*weyk-"},
	{"victim", "*weyk-"},
	{"victor", "*weyk-"},
	{"Victoria", "*weyk-"},
	{"victory", "*weyk-"},
	{"mature", "*meh₂-"},
	{"saw", "*sek-"},
	{"sector", "*sek-"},
	{"segment", "*sek-"},
	{"signal", "*sek-"},
	{"signature", "*sek-"},
	{"avatar", "*terh₂-"},
	{"term", "*terh₂-"},
	{"terminal", "*terh₂-"},
	{"transaction", "*terh₂-"},
	{"ball", "*gʷelH-"},
	{"devil", "*gʷelH-"},
	{"symbol", "*gʷelH-"},
	{"volleyball", "*gʷelH-"},
	{"band", "*bʰendʰ-"},
	{"bend", "*bʰendʰ-"},
	{"bond", "*bʰendʰ-"},
	{"bundle", "*bʰendʰ-"},
	{"bee", "*bʰewgʰ-"},
	{"bought", "*bʰewgʰ-"},
	{"bow", "*bʰewgʰ-"},
	{"rainbow", "*bʰewgʰ-"},
	{"blade", "*bʰleh₃-"},
	{"blow", "*bʰleh₃-"},
	{"floral", "*bʰleh₃-"},
	{"flower", "*bʰleh₃-"},
	{"central", "*-trom"},
	{"monster", "*-trom"},
	{"spectrum", "*-trom"},
	{"theater", "*-trom"},
	{"claim", "*kelh₁-"},
	{"clarity", "*kelh₁-"},
	{"clear", "*kelh₁-"},
	{"council", "*kelh₁-"},
	{"client", "*ḱlew-"},
	{"listen", "*ḱlew-"},
	{"loud", "*ḱlew-"},
	{"Louis", "*ḱlew-"},
	{"cold", "*gel-"},
	{"cool", "*gel-"},
	{"gel", "*gel-"},
	{"globe", "*gel-"},
	{"column", "*kelH-"},
	{"excel", "*kelH-"},
	{"excellent", "*kelH-"},
	{"hill", "*kelH-"},
	{"command", "*(s)meh₂-"},
	{"demand", "*(s)meh₂-"},
	{"manner", "*(s)meh₂-"},
	{"manual", "*(s)meh₂-"},
	{"conjunction", "*yewg-"},
	{"joint", "*yewg-"},
	{"junction", "*yewg-"},
	{"yoga", "*yewg-"},
	{"corporate", "*krep-"},
	{"corporation", "*krep-"},
	{"corps", "*krep-"},
	{"incorporate", "*krep-"},
	{"dairy", "*dʰeyǵʰ-"},
	{"fiction", "*dʰeyǵʰ-"},
	{"figure", "*dʰeyǵʰ-"},
	{"lady", "*dʰeyǵʰ-"},
	{"defend", "*gʷʰen-"},
	{"defense", "*gʷʰen-"},
	{"gun", "*gʷʰen-"},
	{"offense", "*gʷʰen-"},
	{"describe", "*(s)kreybʰ-"},
	{"script", "*(s)kreybʰ-"},
	{"subscribe", "*(s)kreybʰ-"},
	{"transcript", "*(s)kreybʰ-"},
	{"diary", "*dyew-"},
	{"divine", "*dyew-"},
	{"journal", "*dyew-"},
	{"journey", "*dyew-"},
	{"earn", "*seh₁-"},
	{"season", "*seh₁-"},
	{"seed", "*seh₁-"},
	{"seminar", "*seh₁-"},
	{"engage", "*wedʰ-"},
	{"mortgage", "*wedʰ-"},
	{"wage", "*wedʰ-"},
	{"wed", "*wedʰ-"},
	{"fellow", "*legʰ-"},
	{"lay", "*legʰ-"},
	{"layer", "*legʰ-"},
	{"lie", "*legʰ-"},
	{"field", "*pleth₂-"},
	{"flat", "*pleth₂-"},
	{"plate", "*pleth₂-"},
	{"plaza", "*pleth₂-"},
	{"grammar", "*gerbʰ-"},
	{"graph", "*gerbʰ-"},
	{"graphic", "*gerbʰ-"},
	{"photograph", "*gerbʰ-"},
	{"honest", "*-tós"},
	{"justice", "*-tós"},
	{"robust", "*-tós"},
	{"tribute", "*-tós"},
	{"injury", "*h₂yew-"},
	{"judge", "*h₂yew-"},
	{"jury", "*h₂yew-"},
	{"justice", "*h₂yew-"},
	{"inter", "*ters-"},
	{"terrace", "*ters-"},
	{"territory", "*ters-"},
	{"test", "*ters-"},
	{"invest", "*wes-"},
	{"investment", "*wes-"},
	{"wear", "*wes-"},
	{"pain", "*kʷey-"},
	{"penalty", "*kʷey-"},
	{"pine", "*kʷey-"},
	{"punishment", "*kʷey-"},
	{"passion", "*peh₁-"},
	{"patient", "*peh₁-"},
	{"quick", "*gʷeyh₃-"},
	{"survive", "*gʷeyh₃-"},
	{"vital", "*gʷeyh₃-"},
	{"vitamin", "*gʷeyh₃-"},
	{"valve", "*welH-"},
	{"walk", "*welH-"},
	{"wall", "*welH-"},
	{"variety", "*h₁weh₂-"},
	{"vast", "*h₁weh₂-"},
	{"void", "*h₁weh₂-"},
	{"waste", "*h₁weh₂-"},
	{"vector", "*weǵʰ-"},
	{"vehicle", "*weǵʰ-"},
	{"via", "*weǵʰ-"},
	{"weight", "*weǵʰ-"},
	{"accurate", "*kʷeys-"},
	{"cure", "*kʷeys-"},
	{"curious", "*kʷeys-"},
	{"advocate", "*wekʷ-"},
	{"vocal", "*wekʷ-"},
	{"voice", "*wekʷ-"},
	{"along", "*h₂en-"},
	{"answer", "*h₂en-"},
	{"antique", "*h₂en-"},
	{"animal", "*h₂enh₁-"},
	{"animation", "*h₂enh₁-"},
	{"anime", "*h₂enh₁-"},
	{"appeal", "*pel-"},
	{"film", "*pel-"},
	{"fold", "*pel-"},
	{"Argentina", "*h₂erǵ-"},
	{"argue", "*h₂erǵ-"},
	{"argument", "*h₂erǵ-"},
	{"ash", "*h₂eHs-"},
	{"disaster", "*h₂eHs-"},
	{"star", "*h₂eHs-"},
	{"auction", "*h₂ewg-"},
	{"august", "*h₂ewg-"},
	{"nickname", "*h₂ewg-"},
	{"Australia", "*h₂ews-"},
	{"east", "*h₂ews-"},
	{"Easter", "*h₂ews-"},
	{"beef", "*gʷṓws"},
	{"buffalo", "*gʷṓws"},
	{"butter", "*gʷṓws"},
	{"blast", "*bʰleh₁-"},
	{"blow", "*bʰleh₁-"},
	{"inflation", "*bʰleh₁-"},
	{"cave", "*ḱewh₁-"},
	{"church", "*ḱewh₁-"},
	{"jail", "*ḱewh₁-"},
	{"cell", "*ḱel- "},
	{"hall", "*ḱel- "},
	{"hell", "*ḱel- "},
	{"census", "*ḱens-"},
	{"comedy", "*ḱens-"},
	{"cosmetic", "*ḱens-"},
	{"chrome", "*gʰer-"},
	{"grand", "*gʰer-"},
	{"gross", "*gʰer-"},
	{"confirm", "*dʰer-"},
	{"confirmation", "*dʰer-"},
	{"firm", "*dʰer-"},
	{"consult", "*selh₁-"},
	{"counsel", "*selh₁-"},
	{"sell", "*selh₁-"},
	{"cook", "*pekʷ-"},
	{"cuisine", "*pekʷ-"},
	{"kitchen", "*pekʷ-"},
	{"corn", "*ǵerh₂-"},
	{"grain", "*ǵerh₂-"},
	{"kernel", "*ǵerh₂-"},
	{"dawn", "*dʰegʷʰ-"},
	{"fever", "*dʰegʷʰ-"},
	{"Sunday", "*dʰegʷʰ-"},
	{"dead", "*dʰew-"},
	{"die", "*dʰew-"},
	{"funeral", "*dʰew-"},
	{"decor", "*deḱ-"},
	{"doctor", "*deḱ-"},
	{"document", "*deḱ-"},
	{"deliver", "*h₁lewdʰ-"},
	{"liberal", "*h₁lewdʰ-"},
	{"liberty", "*h₁lewdʰ-"},
	{"democratic", "*kret-"},
	{"dick", "*kret-"},
	{"hard", "*kret-"},
	{"domestic", "*dem-"},
	{"dominant", "*dem-"},
	{"timber", "*dem-"},
	{"ever", "*perkʷ-"},
	{"farm", "*perkʷ-"},
	{"forest", "*perkʷ-"},
	{"fast", "*peh₂ǵ-"},
	{"impact", "*peh₂ǵ-"},
	{"pole", "*peh₂ǵ-"},
	{"fat", "*peyH-"},
	{"pine", "*peyH-"},
	{"pitch", "*peyH-"},
	{"feet", "*ped-"},
	{"foot", "*ped-"},
	{"football", "*ped-"},
	{"fleet", "*plew-"},
	{"float", "*plew-"},
	{"flood", "*plew-"},
	{"gold", "*ǵʰelh₃-"},
	{"golden", "*ǵʰelh₃-"},
	{"yellow", "*ǵʰelh₃-"},
	{"heart", "*ḱerd-"},
	{"incredible", "*ḱerd-"},
	{"record", "*ḱerd-"},
	{"leave", "*leyp-"},
	{"liver", "*leyp-"},
	{"twelve", "*leyp-"},
	{"marine", "*mer- "},
	{"maritime", "*mer- "},
	{"mere", "*mer- "},
	{"memorabilia", "*(s)mer-"},
	{"memory", "*(s)mer-"},
	{"remember", "*(s)mer-"},
	{"miscellaneous", "*meyḱ-"},
	{"mix", "*meyḱ-"},
	{"mixture", "*meyḱ-"},
	{"nice", "*skey-"},
	{"scientific", "*skey-"},
	{"ski", "*skey-"},
	{"quiet", "*kʷyeh₁-"},
	{"quit", "*kʷyeh₁-"},
	{"whilst", "*kʷyeh₁-"},
	{"red", "*h₁rewdʰ-"},
	{"robust", "*h₁rewdʰ-"},
	{"ruby", "*h₁rewdʰ-"},
	{"sad", "*seh₂-"},
	{"satisfaction", "*seh₂-"},
	{"satisfy", "*seh₂-"},
	{"scheme", "*seǵʰ-"},
	{"scholarship", "*seǵʰ-"},
	{"severe", "*seǵʰ-"},
	{"stop", "*(s)tewp-"},
	{"stupid", "*(s)tewp-"},
	{"typical", "*(s)tewp-"},
	{"strategic", "*sterh₃-"},
	{"strategy", "*sterh₃-"},
	{"street", "*sterh₃-"},
	{"strength", "*strengʰ-"},
	{"string", "*strengʰ-"},
	{"strong", "*strengʰ-"},
	{"student", "*(s)tewd-"},
	{"studio", "*(s)tewd-"},
	{"study", "*(s)tewd-"},
	{"thank", "*teng-"},
	{"thanks", "*teng-"},
	{"thought", "*teng-"},
}
